/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dream` | `/dream`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/brand-explorer` | `/brand-explorer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/completion` | `/completion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/brand-explorer/[brand]` | `/brand-explorer/[brand]`, params: Router.UnknownInputParams & { brand: string | number; } } | { pathname: `${'/(tabs)'}/completion/[countryCode]` | `/completion/[countryCode]`, params: Router.UnknownInputParams & { countryCode: string | number; } } | { pathname: `${'/(tabs)'}/hotel/[id]` | `/hotel/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dream` | `/dream`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/brand-explorer` | `/brand-explorer`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/completion` | `/completion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/brand-explorer/[brand]` | `/brand-explorer/[brand]`, params: Router.UnknownOutputParams & { brand: string; } } | { pathname: `${'/(tabs)'}/completion/[countryCode]` | `/completion/[countryCode]`, params: Router.UnknownOutputParams & { countryCode: string; } } | { pathname: `${'/(tabs)'}/hotel/[id]` | `/hotel/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dream${`?${string}` | `#${string}` | ''}` | `/dream${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/brand-explorer${`?${string}` | `#${string}` | ''}` | `/brand-explorer${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/completion${`?${string}` | `#${string}` | ''}` | `/completion${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dream` | `/dream`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/brand-explorer` | `/brand-explorer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/completion` | `/completion`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/brand-explorer/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/brand-explorer/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/completion/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/completion/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hotel/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/hotel/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/brand-explorer/[brand]` | `/brand-explorer/[brand]`, params: Router.UnknownInputParams & { brand: string | number; } } | { pathname: `${'/(tabs)'}/completion/[countryCode]` | `/completion/[countryCode]`, params: Router.UnknownInputParams & { countryCode: string | number; } } | { pathname: `${'/(tabs)'}/hotel/[id]` | `/hotel/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
